# Generated by Django 5.0.1 on 2024-05-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quiz",
            old_name="numer_of_questions",
            new_name="number_of_questions",
        ),
        migrations.AlterField(
            model_name="quiz",
            name="name",
            field=models.CharField(help_text="nom de quiz", max_length=120),
        ),
    ]
